[[configuration-settings]]
= Configuration Settings Reference

On this page you'll find the main configuration settings you can use with Neo4j.
They can be set in <<file-locations, _neo4j.conf_>> when using the Neo4j Server (see <<server-configuration>>).
If you use the embedded database, you can pass them in as a map (see <<tutorials-java-embedded-setup-config>>).

For additional configuration settings, see:

* <<server-configuration>>
* <<config-org.neo4j.shell.ShellSettings>>
* <<config-org.neo4j.kernel.ha.HaSettings>>
* <<config-org.neo4j.cluster.ClusterSettings>>
* <<config-org.neo4j.backup.OnlineBackupSettings>>
* <<config-org.neo4j.consistency.ConsistencyCheckSettings>>
* <<config-org.neo4j.ext.udc.UdcSettings>>
* <<config-org.neo4j.metrics.MetricsSettings>>


include::configuration-attributes.asciidoc[]

== Configuring Bolt Connectors

Bolt Connectors are ports that accept connections via the Bolt Database Protocol, which is the protocol used by official Neo4j Driver Libraries.
You can configure Neo4j with one or more connectors, allowing you, for instance, to mandate encryption for remote connections.

If you are using Neo4j Embedded, you need to include the Bolt extension on your class path.

Each connector has a unique key to identify it, denoted `{key}` in the listing below.

include::configuration-attributes.asciidoc[]
